default_language_version:
  python: python3.11
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: \.(xml|svg)$
    - id: trailing-whitespace
      exclude: \.(xml|md|svg|html)$
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      args: ['--no-verify', "--exclude-secrets", "(testsecret|${.*})"]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      args: ["--line-length=119"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile","black", "--filter-files","--line-length=72"]
- repo: https://github.com/PyCQA/flake8.git
  rev: 6.1.0
  hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.0
  hooks:
    - id: mypy
      args: ["--ignore-missing-imports", "--no-site-packages", "--no-strict-optional", "--python-version=3.11", "--disallow-incomplete-defs", "--check-untyped-defs"]
      additional_dependencies:
        - "pydantic>=1.10.4"
